
sudo: required

language: java

dist:
  - trusty

jdk:
  - openjdk7

os:
  - linux

group:
  - stable

before_cache:
  - sudo rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - sudo rm -fr $HOME/.gradle/caches/*/plugin-resolution

cache:
  directories:
    - $HOME/.gradle/wrapper
    - $HOME/.gradle/native
    - $HOME/.gradle/daemon
    - $HOME/.gradle/caches

branches:
  only:
    - master

before_script:
  - chmod +x gradlew

script:
  - sudo ./gradlew clean build -x test --info --no-daemon
  - sudo ./gradlew codeCoverageReport

after_success:
  - sudo bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - ardikars@gmail.com
    on_success: change
    on_failure: always
