
version: '{build}-{branch}'

branches:
  only:
    - master
  except:
    - development

skip_tags: true

os: Windows Server 2012 R2

shallow_clone: true

cache:
  - C:\Users\appveyor\.gradle\wrapper
  - C:\Users\appveyor\.gradle\native
  - C:\Users\appveyor\.gradle\daemon
  - C:\Users\appveyor\.gradle\caches

install:
  - cmd: choco install -y nmap

platform: Any CPU

build_script:
  - cmd: gradlew.bat clean build -x test --info --no-deamon

test_script:
  - cmd: gradlew.bat clean test codeCoverageReport --info --no-deamon

notifications:
  - provider: Email
    to: contact@ardikars.com
    on_build_success: false
    on_build_failure: true

