
#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: '{build}-{branch}'

branches:
  only:
    - master
  except:
    - development

# Do not build on tags
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Windows Server 2012 R2

# fetch repository as zip archive
shallow_clone: true

cache:
  - C:\Users\appveyor\.gradle\wrapper
  - C:\Users\appveyor\.gradle\native
  - C:\Users\appveyor\.gradle\daemon
#  - C:\Users\appveyor\.gradle\caches

# environment variables
environment:
  JAVA_HOME: C:\Program Files (x86)\Java\jdk1.7.0

# scripts that run after cloning repository
install:
  # Install WinPcap
  #- cmd: choco install -y winpcap
  - ps: .\.scripts\InstallNpcap.ps1

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

build_script:
  - cmd: gradlew.bat clean build -x test --info --no-daemon

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:
  - cmd: gradlew.bat clean codeCoverageReport --info --no-daemon

after_test:
  - cmd: gradlew.bat clean --info --no-daemon

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:
  - provider: Email
    to: ardikars@gmail.com
    on_build_success: false
    on_build_failure: true
    